casdoor/casdoor-dotnet-sdk

.github/workflows/build.yml
src/Casdoor.Client/Extensions/CasdoorOptionsExtension.cs

fix: Cannot auto discovery OIDC configuration by http url

---

samples/ConsoleApp/Program.cs
src/Casdoor.Client/CasdoorClient.AccountApi.cs

Fix: #21 
Add a model to support the password reset.
Related Issue: #21
1. Add model for changing password.
2. Add corresponding sample code.
3. It seems there is a spelling mistake in the existing sample which write "built-in" as "build-in". I changed it so that the test can succeed. If it is in fact not a BUG, I will remove this change.

feat: Add model for changing password.

---

src/Casdoor.Client/Abstractions/ICasdoorModelClient.cs
src/Casdoor.Client/Abstractions/ICasdoorUserClient.cs
src/Casdoor.Client/CasdoorClient.ModelApi.cs
src/Casdoor.Client/CasdoorClient.UserApi.cs
src/Casdoor.Client/Models/CasdoorModel.cs

feat: Added apis for User and Model

feat: Add apis for User and Model

---

src/Casdoor.AspNetCore/CasdoorIdentity.cs
src/Casdoor.AspNetCore/ServiceExtension.cs
src/Casdoor.Client/Abstractions/ICasdoorUserClient.cs
src/Casdoor.Client/CasdoorCantants.cs
src/Casdoor.Client/CasdoorClient.UserApi.cs

Add support for Aspnetcore Identity. #27 
Fix: https://github.com/casdoor/casdoor-dotnet-sdk/issues/27
The comments is kept in the code now for convenience of code review. I'll remove them before the merge.

feat: add support for Aspnetcore Identity.

---

README.md
src/Casdoor.Client/CasdoorClient.PermissionApi.cs
src/Casdoor.Client/CasdoorClient.RoleApi.cs
src/Casdoor.Client/Models/CasdoorPermission.cs
src/Casdoor.Client/Models/CasdoorResponse.cs
src/Casdoor.Client/Models/CasdoorRole.cs

example of usage:
var roles = await client.GetRolesAsync();
var perm = (await client.GetPermissionsByRoleAsync(roles.First().Name))?.Data;
var permissions = await client.GetPermissionsAsync();

feat: add roleModel, permissionModel, roleApi, permissionApi

---

README.md
src/Casdoor.Client/CasdoorClient.EnforceApi.cs
src/Casdoor.Client/CasdoorClient.TokenApi.cs
src/Casdoor.Client/Models/CasdoorPermissionRule.cs
src/Casdoor.Client/Models/CasdoorUser.cs

Related to https://github.com/casdoor/casdoor-dotnet-sdk/issues/35

feat: add support for enforce API

---

src/Casdoor.Client/Abstractions/ICasdoorApplicationClient.cs
src/Casdoor.Client/Abstractions/ICasdoorOrganizationClient.cs
src/Casdoor.Client/CasdoorClient.ApplicationApi.cs
src/Casdoor.Client/CasdoorClient.OrganizationApi.cs
src/Casdoor.Client/Models/CasdoorApplication.cs
src/Casdoor.Client/Models/CasdoorOrganization.cs

feat: Added apis for Application and Organization
Fix: https://github.com/casdoor/casdoor-dotnet-sdk/issues/39

feat: add Application and Organization APIs

---

samples/ConsoleApp/Program.cs
src/Casdoor.AspNetCore/CasdoorIdentity.cs
src/Casdoor.Client/Abstractions/ICasdoorApplicationClient.cs
src/Casdoor.Client/Abstractions/ICasdoorOrganizationClient.cs
src/Casdoor.Client/Abstractions/ICasdoorProviderClient.cs
src/Casdoor.Client/Casdoor.Client.csproj.DotSettings
src/Casdoor.Client/CasdoorClient.ApplicationApi.cs
src/Casdoor.Client/CasdoorClient.OrganizationApi.cs
src/Casdoor.Client/CasdoorClient.ProviderApi.cs
src/Casdoor.Client/CasdoorConstants.cs
src/Casdoor.Client/Extensions/QueryMapBuilder.cs
src/Casdoor.Client/Models/CasdoorApplication.cs
src/Casdoor.Client/Models/CasdoorOrganization.cs
src/Casdoor.Client/Models/CasdoorProvider.cs

Fix: https://github.com/casdoor/casdoor-dotnet-sdk/issues/39

feat: API for applications, organizations and providers

---

.github/workflows/release.yml

Fixes #43 
It will auto-release when PR was be merged.

feat: Change to auto-release on push

---

src/Casdoor.Client/Abstractions/ICasdoorAccountClient.cs
src/Casdoor.Client/CasdoorClient.AccountApi.cs
src/Casdoor.Client/CasdoorConstants.cs
src/Casdoor.Client/Extensions/CasdoorResponseExtension.cs
src/Casdoor.Client/Models/CasdoorLdap.cs

Added methods for working with ldap and casdoor response deserialize extension

feat: added LDAP methods

---

src/Casdoor.Client/CasdoorClient.ApplicationApi.cs
src/Casdoor.Client/CasdoorClient.PermissionApi.cs
src/Casdoor.Client/CasdoorClient.ProviderApi.cs
src/Casdoor.Client/CasdoorClient.RoleApi.cs
src/Casdoor.Client/CasdoorClient.UserApi.cs

Hi! Fixed api, jsons now deserializing into CasdoorResponse
Fix: https://github.com/casdoor/casdoor-dotnet-sdk/issues/54

feat: support CasdoorResponse

---

src/Casdoor.AspNetCore/Casdoor.AspNetCore.csproj
src/Casdoor.AspNetCore/ServiceExtension.cs

Fix: https://github.com/casdoor/casdoor-dotnet-sdk/issues/46
Fix: https://github.com/casdoor/casdoor-dotnet-sdk/issues/32

feat: Support AddCasdoorWebApi method

---

src/Casdoor.Client/CasdoorClient.CasbinApi.cs

Test code:
```c#
using Casdoor.Client;
using ConsoleApp;
var httpClient = new HttpClient();
var options = new CasdoorOptions
{
// Require: Basic options
Endpoint = "http://localhost:8000",
OrganizationName = "built-in",
ApplicationName = "app-built-in",
ApplicationType = "native", // webapp, webapi or native
ClientId = "3edff1676210cca28d24",
ClientSecret = "9f918ff437282d2eebf94777208e61227d39edd8",
// Optional: The callback path that the client will be redirected to
// after the user has authenticated. default is "/casdoor/signin-callback"
CallbackPath = "/callback",
// Optional: Whether require https for casdoor endpoint
RequireHttpsMetadata = false,
// Optional: The scopes that the client is requesting.
Scope = "openid profile email"
// More options can be found at README.md
// …
```

fix: enforce methods

---

src/Casdoor.Client/CasdoorClient.CasbinApi.cs

Closes https://github.com/casdoor/casdoor-dotnet-sdk/issues/76

fix: fix Enforce() API response

---

src/Casdoor.Client/Abstractions/ICasdoorProviderClient.cs
src/Casdoor.Client/CasdoorClient.ProviderApi.cs
src/Casdoor.Client/CasdoorConstants.cs

Closes https://github.com/casdoor/casdoor-dotnet-sdk/issues/79

feat: extended casdoor provider api to pass custom owner

---

tests/Casdoor.Client.UnitTests/ApiClientTests/ApplicationTest.cs
tests/Casdoor.Client.UnitTests/Fixtures/ServicesFixture.cs

1. add Endpoint, ClientSecret and etc this time.

ci: add unit test for Application functions

---

src/Casdoor.Client/Abstractions/ICasdoorClient.cs
src/Casdoor.Client/Abstractions/ICasdoorModelClient.cs
tests/Casdoor.Client.UnitTests/ApiClientTests/ModelTest.cs

fix: add model API and tests

---

src/Casdoor.Client/Abstractions/ICasdoorAccountClient.cs
src/Casdoor.Client/Abstractions/ICasdoorClient.cs
src/Casdoor.Client/CasdoorClient.AccountApi.cs
src/Casdoor.Client/CasdoorClient.CasbinApi.cs
src/Casdoor.Client/CasdoorClient.TokenApi.cs
src/Casdoor.Client/CasdoorClient.cs
src/Casdoor.Client/Extensions/CasdoorOptionsExtension.cs
src/Casdoor.Client/Options/CasdoorOptions.cs
tests/Casdoor.Client.UnitTests/ApiClientTests/ClientTest.cs
tests/Casdoor.Client.UnitTests/ApiClientTests/TokenTest.cs
tests/Casdoor.Client.UnitTests/Fixtures/ServicesFixture.cs

feat: add GetSigninUrl Api 

---

.github/workflows/build.yml
.github/workflows/release.yml
tests/Casdoor.Client.UnitTests/ApiClientTests/ClientTest.cs

fix: remove my get to fix ci error

feat: remove MyGet to fix CI error

---

src/Casdoor.AspNetCore/ServiceExtension.cs

fix webapi RequireHttpsMetadata for local dev

feat: fix webapi RequireHttpsMetadata for local dev
